baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
#theme = 'ananke'
theme = ["github.com/onweru/compose"]

[module]

  [[module.imports]]
    path = "github.com/onweru/compose"
    disable = false
